# Nama workflow Anda, akan muncul di tab "Actions" di GitHub
name: Belajar GitHub Actions CI untuk Node js

# Menentukan event yang akan memicu workflow ini
# Dalam kasus ini, workflow akan berjalan setiap kali ada 'push'
on: [push]

# Mendefinisikan satu atau lebih pekerjaan (jobs) yang akan dijalankan
jobs:
  # Nama job (bisa apa saja)
  build:
    # Menentukan sistem operasi untuk runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    # Langkah-langkah yang akan dieksekusi dalam job ini
    steps:
      # Step 1: Menggunakan action 'checkout' untuk mengunduh kode repositori Anda ke runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Menyiapkan Node.js sesuai versi dari matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Menggunakan cache untuk mempercepat instalasi dependensi
          cache: 'npm'

      # 3. Menginstal dependensi proyek
      # 'npm ci' lebih cepat dan aman untuk lingkungan CI daripada 'npm install'
      - name: Install dependencies
        run: npm ci

      # 4. (Opsional) Menjalankan tes. Kita akan tambahkan ini nanti.
      # - name: Run tests
      #   run: npm test